
[dragonlib_common_config]

	[dragonlib_common_config.caching]
		#Specifies how aggressively data should be cached. The lower the value, the less data will be cached, which can reduce RAM usage. However, depending on the situation, less caching can lead to increased CPU usage and cause lag. Only works with mods that actively use the feature! If in doubt, leave unchanged. (Default: NORMAL, OFF = only the most important data will be cached)
		#Allowed Values: NORMAL, REDUCED, MINIMAL, OFF
		mode = "NORMAL"

	[dragonlib_common_config.debug]
		#Prints addidional information about the networking system in the console. For debugging purposes. (Default: OFF)
		networking_logging = false

	[dragonlib_common_config.time_system]
		#When enabled, DragonLib automatically adjusts the time system, depending on which time modification mod is installed and whether a compat is available for it. (Default: ON)
		auto_adjustment = true
		#in Ticks
		#The number of ticks per Minecraft day. This value is overridden if [Auto Adjustment] is enabled. (Default: 24000)
		#Range: 1 ~ 9223372036854775807
		ticks_per_day = 24000
		#in Ticks Per Second
		#The ticks per second at which time of day advances. This value is overridden when [Auto Adjustment] is enabled or when time zones are defined. (Default: 20)
		#Range: 0.0 ~ 2.147483647E9
		ticks_per_second = 20.0
		#The proportion of the total day duration by which the clock time is shifted. By default, 0 ticks = 06:00, for which the time must be shifted by 25% of the day length. (Default: 0.25)
		#Range: 0.0 ~ 1.0
		daytime_shift = 0.25

